site_name: Shift

theme:
# Note: other themes available: mkdocs, material
  name: readthedocs
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - content.tooltips
  language: en
  #logo: images/shift_icon_window.png
  #favicon: images/shift_icon_window.png
  palette:
    scheme: slate
    primary: light blue
    accent: deep purple
  icon:
    repo: fontawesome/brands/github
extra_css:
  - /stylesheets/extra.css
use_directory_urls: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/inbibo-ltd/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@inbibo9227/featured
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/people/Inbibo/100064064923495/
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "75%"
        
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2024 <a href="https://www.inbibo.co.uk/"  target="_blank" rel="noopener">Inbibo LTD</a>

# Page tree
nav:
  - Introduction:               index.md
  - Getting Started:
    - Installation:             getting_started/installation.md
    - Licensing:                getting_started/licensing.md
    - Requirements:             getting_started/requirements.md
    - Shift Basics:
      - Terminology:            getting_started/basics/terminology.md
      - UI Overview:            getting_started/basics/ui_overview.md
      - Workflow Authoring:     getting_started/basics/authoring.md
      - Workflow Execution:     getting_started/basics/execute.md
      - Workflow Debugging:     getting_started/basics/debug.md
      - Nesting Workflows:      getting_started/basics/nesting_workflows.md
      - Batch Execution:        getting_started/basics/batch.md
    - FAQ:                      getting_started/faq.md
  - Reference: 
    - Nodes:                    
      - reference/nodes.md
      - Python Script Node:     reference/nodes/python_script.md
      - Iteration Nodes:        reference/nodes/iterator.md
      - Workflow Nodes:         reference/nodes/workflow.md
      - Variable Node:          reference/nodes/variable.md
      - Conditional Node:       reference/nodes/conditional.md
    - Catalogs:                 reference/catalogs.md
    - Plugins:                  reference/plugins.md
    - Notes:                    reference/notes.md
    - Logger:                   reference/logger.md
    - Enviorment Variables:     reference/enviorment.md
    - Developer Guide:        
      - reference\dev_help\api_standalone.md
      - Shift Python API:         reference/api.md
  - Integrations & Resources:
    - integration_resources/integrations_resources.md
    - Software Platforms:
      - Maya:                     integration_resources/software/maya.md
      - Houdini:                  integration_resources/software/houdini.md
      - Nuke:                     integration_resources/software/nuke.md
      - Resolve:                  integration_resources/software/resolve.md
      - Deadline:                 integration_resources/software/deadline.md
    - Other Resources:
      - USD:                      integration_resources/resources/usd.md
      - Ftrack:                   integration_resources/resources/ftrack.md
  - Release Notes:
    - Release Notes:            release_notes.md
